# This is the main CI pipeline. It builds the Docker image on every
# occasion, but only pushes it to the registry when ran on master.
name: pipeline

# Run when a commit is pushed, a pull request is started or updated and
# when asked to run manually using the Actions tab
on: [ push, pull_request, workflow_dispatch ]

jobs:
# Build the Docker image and optionally push it to the GitHub Container Registry
  build_push:
    runs-on: ubuntu-latest

    steps:
        # Check out the repository in the $GITHUB_WORKSPACE folder
      - uses: actions/checkout@v2
        # Get the short hash for the current commit (to use later)
      - id: git_sha
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        # Get the tag to use for the Docker image, depending on which branch we're on
      - id: image_tag
        run: |
          if [ ${{ github.ref }} == "refs/heads/master" ]
          then echo "::set-output name=tag::latest"
          else echo "::set-output name=tag::rc"
          fi
        # Login to the GitHub Container Registry, so that we can push the image
      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        # Build and push the image
      - name: Build and push Docker image
        uses: docker/build-push-action@v2.3.0
        with:
          # Always pull for the latest base images
          pull: true 
          # Push the image if on the master or rc branch
          push: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/rc' }} 
          # Push to the latest tag and to a tag that is the commit hash
          tags: |
            ghcr.io/creativeprogrammingatelier/atelier-pmd:${{ steps.image_tag.outputs.tag }}
            ghcr.io/creativeprogrammingatelier/atelier-pmd:${{ steps.git_sha.outputs.sha_short }}
